---
server:
  port: 3000
  prefix: "manifest"
name_concat:
  catchup: timeshifting
  startover: 'timeshifting'
catchup_replace: ''
redis:
  host: localhost
  port: 6379
fs:
  prefix: /Users/vietanha34/Documents/workspace/nodejs/manifest-service/test