#!/bin/sh
CI_REGISTRY_IMAGE=$1
BASE_IMAGE=$2
DOCKER_REGISTRY_IMAGE=$3
CI_COMMIT_SHORT_SHA=$4
PACKAGE_VERSION=$(cat ./package.json |
  grep version |
  head -1 |
  awk -F: '{ print $2 }' |
  sed 's/[",]//g' |
  tr -d '[[:space:]]')

CONTAINER_RELEASE_IMAGE=$CI_REGISTRY_IMAGE\:$PACKAGE_VERSION
CONTAINER_DEV_IMAGE=$CI_REGISTRY_IMAGE\:$CI_COMMIT_SHORT_SHA
DOCKER_HUB_RELEASE_IMAGE=$DOCKER_REGISTRY_IMAGE\:$PACKAGE_VERSION
docker build -f ./Dockerfile -t $CONTAINER_RELEASE_IMAGE --build-arg BASE_IMAGE="$BASE_IMAGE" .
docker tag $CONTAINER_RELEASE_IMAGE $DOCKER_HUB_RELEASE_IMAGE
docker tag $CONTAINER_RELEASE_IMAGE $CONTAINER_DEV_IMAGE